defaults: &defaults
  docker:
    - image: wscandy/ci-docker
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build Images
          command: |
              docker build -t $DOCKERHUB_USER/ci-base .
  build_tagged:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Images
          command: |
              mkdir -p docker_cache
              docker build -t $DOCKERHUB_USER/ci-base:$CIRCLE_TAG -t $DOCKERHUB_USER/ci-base .
              docker save -o docker_cache/$CIRCLE_TAG.tar $DOCKERHUB_USER/ci-base:$CIRCLE_TAG
              docker save -o docker_cache/ci-base.tar $DOCKERHUB_USER/ci-base
      - persist_to_workspace:
          root: .
          paths:
            - docker_cache
  push:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Push Images
          command: |
              docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
              docker load < docker_cache/$CIRCLE_TAG.tar
              docker push $DOCKERHUB_USER/ci-base:$CIRCLE_TAG
              docker load < docker_cache/ci-base.tar
              docker push $DOCKERHUB_USER/ci-base

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - build_tagged:
          context: wscandy
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - push:
          context: wscandy
          requires:
            - build_tagged
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/